name: kenwell_health_app
description: A wellness calendar app
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinbox: ^0.13.1
  dropdown_search: ^6.0.2
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  intl: 0.20.2
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  signature: ^6.3.0
  path_provider: ^2.1.5
  cloud_firestore: ^6.0.3
  flutter_animate: ^4.5.2
  uuid: ^4.5.2
  drift: ^2.21.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.40
  path: ^1.9.0
  fl_chart: ^1.1.1
  fluttertoast: ^9.0.0
  permission_handler: ^11.3.1
  flutter_slidable: ^3.1.1
  sizer: ^2.0.15
  excel: ^4.0.6
  go_router: ^14.6.2
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.21.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/kenwell_logo.png
    - assets/app_logo.jpg